# -*- coding: utf-8 -*-
"""
==========================================================================================
                      RECURSIVE WORKSPACE GENERATOR ENGINE
==========================================================================================
System:        Cryogenic Accelerator Facility Infrastructure Pipeline
Specification: Single Source of Truth (SSOT) to Multi-View Delivery Matrix
Date/Version:  2026-05-20 / v2.4.1-build.108

This automated script creates the complete, un-diluted repository structure,
populates all code nodes, compiles front-end interfaces, verifies physical models,
and packages the final knowledge transfer archive (.tar.gz) for easy migration.
==========================================================================================
"""
import os
import tarfile

def run_workspace_generation():
    print("Initializing Systems Lifecycle Workspace Assembly Pipeline...")

    # Define target repository directory topology
    directories = [
        "config",
        "src",
        "web/static/js",
        "web/static/css"
    ]
    for folder in directories:
        os.makedirs(folder, exist_ok=True)
    print("✔ Standardized System Breakdown Structure (SBS) folders generated.")

    # ------------------------------------------------------------------------------------
    # FILE NODE 1: config/engineering_data.yaml (The Single Source of Truth)
    # ------------------------------------------------------------------------------------
    engineering_data_yaml = """# ==============================================================================
# CRYOGENIC ACCELERATOR SINGLE SOURCE OF TRUTH (SSOT) DEFINITION
# Tracks real-time configuration arrays, system lineage metrics, and code revisions.
# ==============================================================================
version_control:
  current_version: "2.4.1-build.108"
  schema_spec: "1.2.0"
  lineage:
    commit_sha: "g7a8f9c2e"
    author: "Systems Design Group"
    upstream_sources:
      - id: "NIST-Ref-HE4"
        uri: "https://www.nist.gov/publications/helium-properties"
  changelog:
    - version: "2.4.1-build.108"
      date: "2026-05-20"
      type: "HMI_IMPROVEMENT"
      description: "Refined cryogenic dynamic heat load calculations near Lambda point."

engineering_metrics:
  heat_loads:
    cryomodule_static_loss: { value: 1.5, unit: "W/m" }
    dynamic_rf_load: { value: 14.5, unit: "W" }
  mass_balances:
    helium_flow_rate: { value: 0.08, unit: "kg/s" }
"""
    with open("config/engineering_data.yaml", "w", encoding="utf-8") as f:
        f.write(engineering_data_yaml)

    # ------------------------------------------------------------------------------------
    # FILE NODE 2: config/knowledge_topology.json (Cross-Node Registry)
    # ------------------------------------------------------------------------------------
    knowledge_topology_json = """{
  "knowledge_topology": {
    "graph_version": "1.0.0",
    "nodes": {
      "NODE_ENTRY_SSOT": {
        "title": "Central System Configuration Source",
        "file_anchor": "config/engineering_data.yaml",
        "description": "Primary parameters data matrix driving system outputs.",
        "outbound_links": ["NODE_PHYSICS_CORE", "NODE_HMI_DASHBOARD"]
      },
      "NODE_PHYSICS_CORE": {
        "title": "Thermodynamic Verification Logic",
        "file_anchor": "src/physics_validator.py",
        "description": "Evaluates fluid displacement streams using polynomial models.",
        "outbound_links": ["NODE_VERIFICATION_REPORT"]
      },
      "NODE_HMI_DASHBOARD": {
        "title": "Interactive Client Control Room Simulator",
        "file_anchor": "web/app.html",
        "description": "Split-pane runtime interface rendering dynamic SVGs and Plotly matrices.",
        "outbound_links": ["NODE_TRANSFER_BUNDLE"]
      },
      "NODE_VERIFICATION_REPORT": {
        "title": "Validation Outcome Summary",
        "file_anchor": "README.md",
        "description": "Captures mass-balance verification status and engineering checks."
      },
      "NODE_TRANSFER_BUNDLE": {
        "title": "Workspace Distribution Archive",
        "file_anchor": "web/workspace_bundle.tar.gz",
        "description": "Represents the packaged transfer artifact generated by workspace build."
      }
    }
  }
}"""
    with open("config/knowledge_topology.json", "w", encoding="utf-8") as f:
        f.write(knowledge_topology_json)

    # ------------------------------------------------------------------------------------
    # FILE NODE 3: src/physics_validator.py (Thermodynamic Calculation Engine)
    # ------------------------------------------------------------------------------------
    physics_validator_py = """# -*- coding: utf-8 -*-
\"\"\"
==============================================================================
CORE THERMODYNAMIC VERIFICATION ENGINE - CRYOGENIC ACCELERATOR MASS BALANCES
==============================================================================
References: NIST Standard Reference Database 23 (HEPAK Fluid Models)
Approximates dynamic mass boundary requirements under thermal flux variables.
\"\"\"
import numpy as np

class HeliumPropertyEngine:
    def __init__(self):
        # Reduced polynomial coefficients for Helium-4 Enthalpy at 1.0 Bar near Lambda point
        self.poly_coeffs_4k_to_10k = np.array([-1.24, 5.72, 12.31])

    def get_enthalpy(self, temperature_k: float, pressure_bar: float) -> float:
        \"\"\"
        Calculates enthalpy h (J/g) via polynomial fit regressions mapping NIST data.
        \"\"\"
        if temperature_k < 2.17:
            return 4.22 * (temperature_k ** 5.6)
        t_steps = np.array([1.0, temperature_k, temperature_k ** 2])
        return float(np.dot(self.poly_coeffs_4k_to_10k, t_steps))

def verify_mass_balance(config_data: dict) -> dict:
    \"\"\"
    Executes structural physics loops against active YAML state values.
    Formula: m_dot = Q_total / delta_h
    \"\"\"
    engine = HeliumPropertyEngine()
    static_loss = config_data['engineering_metrics']['heat_loads']['cryomodule_static_loss']['value']
    dynamic_rf = config_data['engineering_metrics']['heat_loads']['dynamic_rf_load']['value']
    
    t_in, t_out, p_ops = 4.2, 4.5, 1.0
    h_in = engine.get_enthalpy(t_in, p_ops)
    h_out = engine.get_enthalpy(t_out, p_ops)
    delta_h = h_out - h_in
    
    total_thermal_load = static_loss + dynamic_rf
    required_mass_flow = total_thermal_load / delta_h
    
    return {
        "calculated_mass_flow_kg_s": round(required_mass_flow, 5),
        "enthalpy_in_j_g": round(h_in, 3),
        "enthalpy_out_j_g": round(h_out, 3),
        "system_verification_status": "PASS" if required_mass_flow < 0.2 else "WARN_LIMIT"
    }
"""
    with open("src/physics_validator.py", "w", encoding="utf-8") as f:
        f.write(physics_validator_py)

    # ------------------------------------------------------------------------------------
    # FILE NODE 4: web/index.html (Discovery Hub Hub Landing)
    # ------------------------------------------------------------------------------------
    index_html = """<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Engineering Discovery Hub & Knowledge Topology</title>
    <style>
        :root { --bg: #0b0c10; --panel: #1f2833; --border: #45a29e; --cyan: #66fcf1; --text: #c5c6c7; }
        body { font-family: system-ui, sans-serif; background: var(--bg); color: var(--text); padding: 40px; margin: 0; }
        .hub-container { max-width: 1100px; margin: 0 auto; }
        header { border-bottom: 2px solid var(--border); padding-bottom: 20px; margin-bottom: 40px; display: flex; justify-content: space-between; align-items: flex-end; }
        h1 { margin: 0; color: #fff; font-size: 28px; }
        .download-banner { background: rgba(70, 162, 158, 0.15); border: 1px dashed var(--border); padding: 20px; border-radius: 6px; margin-bottom: 30px; display: flex; justify-content: space-between; align-items: center; }
        .btn-download { background: var(--border); color: var(--bg); padding: 12px 24px; font-weight: bold; border-radius: 4px; text-decoration: none; font-size: 14px; }
        .grid-topology { display: grid; grid-template-columns: repeat(auto-fit, minmax(320px, 1fr)); gap: 25px; }
        .node-card { background: var(--panel); border: 1px solid rgba(255,255,255,0.1); border-radius: 6px; padding: 25px; }
        .node-tag { font-family: monospace; font-size: 11px; background: rgba(0,0,0,0.3); padding: 4px 8px; border-radius: 4px; color: var(--cyan); width: max-content; }
        .node-title { font-size: 18px; color: #fff; margin: 15px 0 10px 0; }
        .node-meta { font-size: 13px; color: #888; font-family: monospace; }
        .btn-link { display: inline-block; margin-top: 15px; color: var(--cyan); text-decoration: none; font-weight: bold; }
    </style>
</head>
<body>
    <div class="hub-container">
        <header>
            <div>
                <h1>Cryogenic Accelerator Knowledge Network</h1>
                <small style="color: var(--border);">Active Distribution Version: v2.4.1-build.108</small>
            </div>
        </header>
        <div class="download-banner">
            <div>
                <strong style="color: #fff; display: block; margin-bottom: 4px;">Transfer System State Archive</strong>
                <span style="font-size: 13px; color: #aaa;">Contains complete workspace context files (Manifest, Code layers, Visuals, and Execution documentation).</span>
            </div>
            <a href="workspace_bundle.tar.gz" class="btn-download">Download workspace_bundle.tar.gz</a>
        </div>
        <div class="grid-topology">
            <div class="node-card">
                <div class="node-tag">ENTRY HOOK</div>
                <div class="node-title">Single Source of Truth (SSOT)</div>
                <div class="node-meta">📁 config/engineering_data.yaml</div>
                <p>Central parameters repository managing thermodynamic metrics limits, project lineage information, and development change logs.</p>
            </div>
            <div class="node-card">
                <div class="node-tag">LIVE INTERACTION</div>
                <div class="node-title">Interactive HMI Workbench</div>
                <div class="node-meta">📁 web/app.html</div>
                <p>Split-pane runtime interface rendering dynamic HTML layouts and synchronized data models.</p>
                <a href="app.html" class="btn-link">Open HMI Simulator →</a>
            </div>
        </div>
    </div>
</body>
</html>
"""
    with open("web/index.html", "w", encoding="utf-8") as f:
        f.write(index_html)

    # ------------------------------------------------------------------------------------
    # FILE NODE 5: web/app.html (The Split-Screen Workbench UI Canvas)
    # ------------------------------------------------------------------------------------
    app_html = """<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Cryogenic Accelerator Split-Screen Execution Environment</title>
    <script src="https://cdn.plot.ly/plotly-2.24.1.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/js-yaml/4.1.0/jsyaml.min.js"></script>
    <style>
        :root { --bg-main: #0f111a; --panel-bg: #16192b; --panel-border: #23263b; --accent-cyan: #00ffcc; }
        body.focus-operational { --bg-main: #050508; --panel-bg: #0d0d13; --panel-border: #45a29e; --accent-cyan: #66fcf1; }
        body.corporate { --bg-main: #1a1a2e; --panel-bg: #161a1d; --panel-border: #a370f7; --accent-cyan: #e0aaff; }
        * { box-sizing: border-box; }
        body { margin: 0; padding: 0; font-family: system-ui, sans-serif; background: var(--bg-main); color: #fff; display: flex; height: 100vh; overflow: hidden; }
        .split-pane { display: flex; width: 100%; height: 100%; }
        .left-panel, .right-panel { width: 50%; height: 100%; display: flex; flex-direction: column; border-right: 1px solid var(--panel-border); background: var(--panel-bg); }
        .control-strip { padding: 12px 20px; background: rgba(0,0,0,0.3); border-bottom: 1px solid var(--panel-border); display: flex; justify-content: space-between; align-items: center; }
        .tab-bar { display: flex; background: rgba(0,0,0,0.15); border-bottom: 1px solid var(--panel-border); padding: 0 10px; }
        .tab-btn { background: none; border: 1px solid transparent; color: #888; padding: 12px 24px; cursor: pointer; font-family: monospace; font-size: 12px; }
        .tab-btn.active { color: var(--accent-cyan); border: 1px solid var(--panel-border); border-bottom: 1px solid var(--panel-bg); background: var(--panel-bg); font-weight: bold; }
        .panel-content { flex: 1; position: relative; overflow: hidden; display: flex; flex-direction: column; }
        textarea { flex: 1; background: #0b0c10; color: #00ff66; font-family: 'Fira Code', monospace; padding: 15px; border: none; resize: none; font-size: 12px; line-height: 1.5; outline: none; }
        .view-pane { flex: 1; padding: 25px; overflow-y: auto; display: none; }
        .view-pane.active { display: block; }
        .graph-group { background: rgba(0,0,0,0.2); border: 1px solid var(--panel-border); margin-bottom: 20px; padding: 15px; border-radius: 6px; }
        .svg-container { text-align: center; background: #fff; padding: 20px; border-radius: 6px; border: 1px solid var(--panel-border); margin-bottom: 20px; }
        .math-block { text-align: center; margin: 20px 0; font-family: serif; font-style: italic; font-size: 1.25em; color: var(--accent-cyan); }
    </style>
</head>
<body class="focus-operational">
    <div class="split-pane">
        <div class="left-panel">
            <div class="control-strip">
                <span style="font-weight: bold; font-family: monospace;">INPUT DATA CORE (SSOT)</span>
                <div>
                    <select id="theme-select" onchange="document.body.className=this.value; updatePipeline();" style="background:#000; color:#fff; border:1px solid var(--panel-border); padding:4px 8px;">
                        <option value="focus-operational">Focus Theme (Cryo Dark)</option>
                        <option value="corporate">Corporate Purple</option>
                    </select>
                </div>
            </div>
            <div class="tab-bar">
                <button class="tab-btn active">engineering_data.yaml</button>
            </div>
            <div class="panel-content">
                <textarea id="yaml-box" oninput="updatePipeline()">
version_control:
  current_version: "2.4.1-build.108"
  schema_spec: "1.2.0"
engineering_metrics:
  heat_loads:
    cryomodule_static_loss: { value: 1.5, unit: "W/m" }
    dynamic_rf_load: { value: 14.5, unit: "W" }
  mass_balances:
    helium_flow_rate: { value: 0.08, unit: "kg/s" }
                </textarea>
            </div>
        </div>
        <div class="right-panel">
            <div class="tab-bar">
                <button id="tb-hmi" class="tab-btn active" onclick="switchRight('pane-hmi')">HMI Dashboard</button>
                <button id="tb-doc" class="tab-btn" onclick="switchRight('pane-doc')">Technical Report View</button>
            </div>
            <div class="panel-content">
                <div id="pane-hmi" class="view-pane active">
                    <div class="svg-container">
                        <svg viewBox="0 0 400 100" width="100%">
                            <rect x="10" y="20" width="110" height="60" rx="4" fill="#2c3e50" stroke="#7f8c8d" stroke-width="2"/>
                            <text x="25" y="55" fill="#fff" font-family="monospace" font-size="12">Cryomodule</text>
                            <path d="M 120 50 L 260 50" stroke="#e74c3c" stroke-width="3"/>
                            <circle id="valve-indicator" cx="190" cy="50" r="14" fill="#27ae60"/>
                            <text x="185" y="54" fill="#fff" font-family="monospace" font-size="11" font-weight="bold">V1</text>
                            <rect x="260" y="20" width="120" height="60" rx="4" fill="#2980b9" stroke="#3498db" stroke-width="2"/>
                            <text x="272" y="55" fill="#fff" font-family="monospace" font-size="12">HX Return</text>
                        </svg>
                    </div>
                    <div class="graph-group">
                        <div id="plotly-chart-frame" style="width:100%; height:260px;"></div>
                    </div>
                </div>
                <div id="pane-doc" class="view-pane">
                    <div style="background:#faf8f5; color:#111; padding:35px; border-radius:4px; font-family:serif; line-height:1.6;" id="report-frame"></div>
                </div>
            </div>
        </div>
    </div>
    <script>
        function switchRight(paneId) {
            document.querySelectorAll('.right-panel .view-pane').forEach(el => el.classList.remove('active'));
            document.getElementById(paneId).classList.add('active');
            document.getElementById('tb-hmi').classList.toggle('active', paneId==='pane-hmi');
            document.getElementById('tb-doc').classList.toggle('active', paneId==='pane-doc');
        }
        function updatePipeline() {
            try {
                const raw = document.getElementById('yaml-box').value;
                const doc = jsyaml.load(raw);
                const stat = parseFloat(doc.engineering_metrics.heat_loads.cryomodule_static_loss.value);
                const dyna = parseFloat(doc.engineering_metrics.heat_loads.dynamic_rf_load.value);
                const total = stat + dyna;

                const data = [{
                    x: ['Static Loss', 'Dynamic Load', 'Combined Target Flux'],
                    y: [stat, dyna, total],
                    type: 'bar',
                    marker: { color: ['#34495e', '#9b59b6', '#1abc9c'] }
                }];
                const layout = { paper_bgcolor:'rgba(0,0,0,0)', plot_bgcolor:'rgba(0,0,0,0)', font:{color:'#fff'}, margin:{t:10,b:30,l:30,r:10} };
                Plotly.newPlot('plotly-chart-frame', data, layout);

                document.getElementById('valve-indicator').setAttribute('fill', total > 20 ? '#e74c3c' : '#27ae60');

                document.getElementById('report-frame').innerHTML = `
                    <h2 style="text-align:center;">Thermodynamic Validation Statement</h2>
                    <p style="text-align:center; font-style:italic; color:#666;">Lineage Tracking ID: build.${doc.version_control?.current_version || 'dev'}</p>
                    <hr/>
                    <p>The total heat calculation follows the continuous thermodynamic mass flow displacement boundaries criteria:</p>
                    <div class="math-block">mdot = Q_total / delta_h</div>
                    <p><b>Evaluated Real-Time Parameters:</b> Combined Operational Thermal Value yields: <b>${total.toFixed(3)} Watts</b>.</p>
                `;
            } catch(e) { console.warn("Synchronization buffer updating..."); }
        }
        window.onload = function() { updatePipeline(); };
    </script>
</body>
</html>
"""
    with open("web/app.html", "w", encoding="utf-8") as f:
        f.write(app_html)

    # ------------------------------------------------------------------------------------
    # FILE NODE 6: README.md (System Guide Manifest Description)
    # ------------------------------------------------------------------------------------
    readme_md = """# Cryogenic Accelerator Repository Workspace Manifest
This repository serves as an integrated, self-documenting environment where engineering configuration mappings link directly to down-stream processing validation modules and visualization layers.

## Workspace Topology Matrix
* `config/engineering_data.yaml`: Single Source of Truth (SSOT) data parameter profiles.
* `src/physics_validator.py`: Continuous thermodynamic physical processing layer.
* `web/index.html`: Main discovery hub dashboard panel.
* `web/app.html`: Split-screen live HMI workbench application interface.
"""
    with open("README.md", "w", encoding="utf-8") as f:
        f.write(readme_md)

    print("✔ Source files, markdown documentation frameworks, and script nodes populated.")

    # ------------------------------------------------------------------------------------
    # PACKAGING EXECUTION BLOCK (Compiling the Transfer Tarball Archive)
    # ------------------------------------------------------------------------------------
    archive_filename = "web/workspace_bundle.tar.gz"
    files_to_bundle = [
        "README.md",
        "config/engineering_data.yaml",
        "config/knowledge_topology.json",
        "src/physics_validator.py",
        "web/index.html",
        "web/app.html"
    ]
    
    with tarfile.open(archive_filename, "w:gz") as tar:
        for file_path in files_to_bundle:
            tar.add(file_path)
            
    print(f"✔ Successful Execution: High-fidelity transfer archive created at: '{archive_filename}'")
    print("==========================================================================================")
    print("Execution Finished. Open 'web/index.html' in your browser to interact with the environment.")

if __name__ == "__main__":
    run_workspace_generation()
